# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
env APP_HOME=/app
WORKDIR $APP_HOME

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Copy source files
COPY src/ ./src/

# Expose port (not strictly necessary for stdio)
EXPOSE 8080

# Default command
entrypoint ["node", "src/index.js"]
